import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
    src: './fonts/Montserrat.ttf',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata = {
    title: 'VIEF',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistSans.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
