import localFont from 'next/font/local';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';

const geistSans = localFont({
    src: './fonts/Montserrat.ttf',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata = {
    title: 'VIEF',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await auth();
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistSans.variable} antialiased`}
            >
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    );
}
